services:
  app:
    build: .
    restart: always
    ports:
      - "5000:80"
    environment:
      VIRTUAL_HOST: ${HOST_DOMAIN}
      LETSENCRYPT_HOST: ${HOST_DOMAIN}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    volumes:
      - app-html:/usr/share/nginx/html
  app-migration:
    build: .
    restart: "no"
    profiles:
      - migration
    command: echo "Running migration tasks..."

volumes:
  app-html:
