version: "3.10"
services:
  app:
    image: nginx:alpine
    restart: always
    ports:
      - "5000:80"
    environment:
      VIRTUAL_HOST: ${HOST_DOMAIN}
      LETSENCRYPT_HOST: ${HOST_DOMAIN}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    volumes:
      - ./html:/usr/share/nginx/html:ro
